# Generated by Django 2.2.7 on 2019-11-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
    ]
